In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
columns = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']
df = pd.read_csv('file/auto-mpg.data', header=None, delimiter=r"\s+",names=columns)

In [3]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

1a) Clean the data [5 pts]
Fix data types
Remove null or undefined values
Drop the column car_name
Replace the data frame with the cleaned data frame. Do not change the column names, and do not add new columns.

In [8]:

df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
dtypes: float64(5), int64(3)
memory usage: 25.0 KB
None
              mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000
mean    23.514573    5.454774    193.425879  104.469388  2970.424623
std      7.815984    1.701004    104.269838   38.491160   846.841774
min      9.000000    3.000000     68.000000   46.000000  1613.000000
25%     17.500000    4.000000    104.250000   75.000000  2223.750000
50%     23.000000    4.000000    148.500000   93.500000  2803.500000
75%     29.000000    8.000000    262.000000  126.000000  3608.000000
max     46.600000    8.000000    455.000000  230.000000  5140.000000

       acceleration  model_year      origin
count    398.000000  398.000000  398.000000
mean      15.568090   76.010050    1.572864
std        2.757689    3.697627    0.802055
min        8.000000   70.000000    1.000000
25%       13.825000   73.000000    1.000000
50%       15.500000   76.000000    1.000000
75%       17.175000   79.000000    2.000000
max       24.800000   82.000000    3.000000
mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [9]:
df['horsepower'].fillna(value=df['horsepower'].mean(),inplace=True)

1b) Fit a simple linear regression model with a feature that maximizes  𝑅2
 . [5 pts]¶
Which feature is the best predictor, and the resulting r-squared value? Update your answer below.

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [11]:
df.corr()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin
mpg,1.000000,-0.775396,-0.804203,-0.771437,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.838939,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.893646,0.932824,-0.543684,-0.370164,-0.609409
horsepower,-0.771437,0.838939,0.893646,1.000000,0.860574,-0.684259,-0.411651,-0.453669
weight,-0.831741,0.896017,0.932824,0.860574,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.684259,-0.417457,1.000000,0.288137,0.205873
model_year,0.579267,-0.348746,-0.370164,-0.411651,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.453669,-0.581024,0.205873,0.180662,1.000000

In [22]:
lr = LinearRegression()
lrx = df['weight']
lry = df['mpg']
xtrain, xtest, ytrain, ytest = train_test_split(lrx, lry, test_size=0.2, random_state=42)

In [24]:
lr.fit(xtrain.values.reshape(-1,1), ytrain)
pred = lr.predict(xtest.values.reshape(-1,1))
print("Mean Squared Error:", mean_squared_error(ytest, pred))
print("R^2 Score:", r2_score(ytest, pred))

Mean Squared Error: 14.894861064636197
R^2 Score: 0.722971057303075

1c) Using the feature found above (without normalizing), fit polynomial regression up to N=10 and report  𝑅2
 . Which polynomial degree gives the best result? [10 pts]
Hint: For N-degree polynomial fit, you have to include all orders upto N. Use a for loop instead of running it manually. The statsmodels.formula.api formula string can understand np.power(x,n) function to include a feature representing  𝑥𝑛
 .

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

for i in range(0,11):
    poly = PolynomialFeatures(degree=i)
    lrx_poly = poly.fit_transform(lrx.values.reshape(-1,1))
    xtrain, xtest, ytrain, ytest = train_test_split(lrx_poly, lry, test_size=0.2, random_state=42)
    lr.fit(xtrain, ytrain)
    pred = lr.predict(xtest)
    print(f"Degree {i} - Mean Squared Error:", mean_squared_error(ytest, pred), "R^2 Score:", r2_score(ytest, pred))

Degree 0 - Mean Squared Error: 53.98329798069697 R^2 Score: -0.00403326341807686
Degree 1 - Mean Squared Error: 14.894861064636197 R^2 Score: 0.722971057303075
Degree 2 - Mean Squared Error: 13.150522130757171 R^2 Score: 0.7554139494160395
Degree 3 - Mean Squared Error: 13.17305256859549 R^2 Score: 0.7549949066773551
Degree 4 - Mean Squared Error: 13.134219135763004 R^2 Score: 0.7557171681870255
Degree 5 - Mean Squared Error: 13.140617326559758 R^2 Score: 0.7555981684847856
Degree 6 - Mean Squared Error: 13.114724840647682 R^2 Score: 0.7560797418250732
Degree 7 - Mean Squared Error: 13.078793141596417 R^2 Score: 0.756748034100797
Degree 8 - Mean Squared Error: 13.087549033240839 R^2 Score: 0.7565851836120212
Degree 9 - Mean Squared Error: 13.225368450704687 R^2 Score: 0.7540218856169991
Degree 10 - Mean Squared Error: 13.590891834365284 R^2 Score: 0.7472235303945449

1d) Now, let's make a new feature called 'weight_norm' which is weight normalized by the mean value. [5 pts]
Run training with polynomial models with polynomial degrees up to 20. Print out each polynomial degree and  𝑅2
  value. What do you observe from the result? What are the best_degree and best_r_qaured just based on  𝑅2
  value? Inspect model summary from each model. What is the highest order model that makes sense (fill the value for the sound_degree)?

Note: For N-degree polynomial fit, you have to include all orders upto N.

In [27]:
df['weight_norm'] = (df['weight'] - df['weight'].mean()) / df['weight'].std()

lrxnorm = df['weight_norm']
xtrain, xtest, ytrain, ytest = train_test_split(lrxnorm, lry, test_size=0.2, random_state=42)
for i in range(0,21):
    poly = PolynomialFeatures(degree=i)
    lrxpoly = poly.fit_transform(lrxnorm.values.reshape(-1,1))
    xtrain, xtest, ytrain, ytest = train_test_split(lrxpoly, lry, test_size=0.2, random_state=42)
    lr.fit(xtrain, ytrain)
    pred = lr.predict(xtest)
    print(f"Degree {i} - Mean Squared Error:", mean_squared_error(ytest, pred), "R^2 Score:", r2_score(ytest, pred))

Degree 0 - Mean Squared Error: 53.98329798069697 R^2 Score: -0.00403326341807686
Degree 1 - Mean Squared Error: 14.894861064636197 R^2 Score: 0.722971057303075
Degree 2 - Mean Squared Error: 13.1505221307728 R^2 Score: 0.7554139494157488
Degree 3 - Mean Squared Error: 13.173052531031814 R^2 Score: 0.7549949073760005
Degree 4 - Mean Squared Error: 13.134204137290078 R^2 Score: 0.7557174471430412
Degree 5 - Mean Squared Error: 13.06136976560588 R^2 Score: 0.7570720907944395
Degree 6 - Mean Squared Error: 13.03972173902547 R^2 Score: 0.7574747216003948
Degree 7 - Mean Squared Error: 12.960629792081614 R^2 Score: 0.7589457496511174
Degree 8 - Mean Squared Error: 12.979878940110359 R^2 Score: 0.758587735494216
Degree 9 - Mean Squared Error: 12.983739862051005 R^2 Score: 0.7585159263569297
Degree 10 - Mean Squared Error: 12.817935927625333 R^2 Score: 0.7615997072965174
Degree 11 - Mean Squared Error: 12.736489197362648 R^2 Score: 0.7631145318707704
Degree 12 - Mean Squared Error: 12.735629654414929 R^2 Score: 0.763130518476686
Degree 13 - Mean Squared Error: 12.535237718672354 R^2 Score: 0.7668576003100009
Degree 14 - Mean Squared Error: 12.422998648070276 R^2 Score: 0.7689451304268143
Degree 15 - Mean Squared Error: 12.420047081790154 R^2 Score: 0.7690000264934734
Degree 16 - Mean Squared Error: 12.312140238067 R^2 Score: 0.7710069816907502
Degree 17 - Mean Squared Error: 12.19815199982429 R^2 Score: 0.773127044508606
Degree 18 - Mean Squared Error: 12.556580814211461 R^2 Score: 0.7664606409046449
Degree 19 - Mean Squared Error: 12.559349273354092 R^2 Score: 0.7664091504405275
Degree 20 - Mean Squared Error: 12.56967775796872 R^2 Score: 0.7662170513561497